exports.layout = { gridSizePixels:10,
    id: 1,
    name:'Couveflor-PUC-1',
    places:[
        { id:3,
            label:'01A',
            numberOfOccupants:1,
            occupied:false,
            rotation:0.071525864538728,
            x:-52,
            y:-19,
            tableId:2,
            tableX:9,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:4,
            label:'01B',
            numberOfOccupants:1,
            occupied:false,
            rotation:45.2975697722287,
            x:-23,
            y:-50,
            tableId:2,
            tableX:9,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:5,
            label:'01C',
            numberOfOccupants:1,
            occupied:false,
            rotation:90.07152586453873,
            x:19,
            y:-52,
            tableId:2,
            tableX:9,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:6,
            label:'01D',
            numberOfOccupants:1,
            occupied:false,
            rotation:135.29756977222868,
            x:50,
            y:-23,
            tableId:2,
            tableX:9,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:7,
            label:'01E',
            numberOfOccupants:1,
            occupied:false,
            rotation:180.07152586453873,
            x:52,
            y:19,
            tableId:2,
            tableX:9,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:8,
            label:'01F',
            numberOfOccupants:1,
            occupied:false,
            rotation:225.2975697722287,
            x:23,
            y:50,
            tableId:2,
            tableX:9,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:9,
            label:'01G',
            numberOfOccupants:1,
            occupied:false,
            rotation:270.0715258645387,
            x:-19,
            y:52,
            tableId:2,
            tableX:9,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:10,
            label:'01H',
            numberOfOccupants:1,
            occupied:false,
            rotation:315.2975697722287,
            x:-50,
            y:23,
            tableId:2,
            tableX:9,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:12,
            label:'09A',
            numberOfOccupants:1,
            occupied:false,
            rotation:0.071525864538728,
            x:-52,
            y:-19,
            tableId:11,
            tableX:34,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:13,
            label:'09B',
            numberOfOccupants:1,
            occupied:false,
            rotation:45.2975697722287,
            x:-23,
            y:-50,
            tableId:11,
            tableX:34,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:14,
            label:'09C',
            numberOfOccupants:1,
            occupied:false,
            rotation:90.07152586453873,
            x:19,
            y:-52,
            tableId:11,
            tableX:34,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:15,
            label:'09D',
            numberOfOccupants:1,
            occupied:false,
            rotation:135.29756977222868,
            x:50,
            y:-23,
            tableId:11,
            tableX:34,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:16,
            label:'09E',
            numberOfOccupants:1,
            occupied:false,
            rotation:180.07152586453873,
            x:52,
            y:19,
            tableId:11,
            tableX:34,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:17,
            label:'09F',
            numberOfOccupants:1,
            occupied:false,
            rotation:225.2975697722287,
            x:23,
            y:50,
            tableId:11,
            tableX:34,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:18,
            label:'09G',
            numberOfOccupants:1,
            occupied:false,
            rotation:270.0715258645387,
            x:-19,
            y:52,
            tableId:11,
            tableX:34,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:19,
            label:'09H',
            numberOfOccupants:1,
            occupied:false,
            rotation:315.2975697722287,
            x:-50,
            y:23,
            tableId:11,
            tableX:34,
            tableY:7,
            tableClass:'models.RoundTable' },
        { id:21,
            label:'21A',
            numberOfOccupants:1,
            occupied:false,
            rotation:-0.14478563067896744,
            x:-72,
            y:-26,
            tableId:20,
            tableX:37,
            tableY:51,
            tableClass:'models.RoundTable' },
        { id:22,
            label:'21B',
            numberOfOccupants:1,
            occupied:false,
            rotation:32.98011374516851,
            x:-46,
            y:-61,
            tableId:20,
            tableX:37,
            tableY:51,
            tableClass:'models.RoundTable' },
        { id:23,
            label:'21C',
            numberOfOccupants:1,
            occupied:false,
            rotation:65.48601154199872,
            x:-6,
            y:-76,
            tableId:20,
            tableX:37,
            tableY:51,
            tableClass:'models.RoundTable' },
        { id:24,
            label:'21D',
            numberOfOccupants:1,
            occupied:false,
            rotation:98.24973549497427,
            x:36,
            y:-67,
            tableId:20,
            tableX:37,
            tableY:51,
            tableClass:'models.RoundTable' },
        { id:25,
            label:'21E',
            numberOfOccupants:1,
            occupied:false,
            rotation:131.09081634885217,
            x:67,
            y:-37,
            tableId:20,
            tableX:37,
            tableY:51,
            tableClass:'models.RoundTable' },
        { id:26,
            label:'21F',
            numberOfOccupants:1,
            occupied:false,
            rotation:163.01278750418334,
            x:76,
            y:4,
            tableId:20,
            tableX:37,
            tableY:51,
            tableClass:'models.RoundTable' },
        { id:27,
            label:'21G',
            numberOfOccupants:1,
            occupied:false,
            rotation:195.97238704928492,
            x:62,
            y:45,
            tableId:20,
            tableX:37,
            tableY:51,
            tableClass:'models.RoundTable' },
        { id:28,
            label:'21H',
            numberOfOccupants:1,
            occupied:false,
            rotation:229.1791071466892,
            x:27,
            y:71,
            tableId:20,
            tableX:37,
            tableY:51,
            tableClass:'models.RoundTable' },
        { id:29,
            label:'21I',
            numberOfOccupants:1,
            occupied:false,
            rotation:261.30993247402023,
            x:-15,
            y:75,
            tableId:20,
            tableX:37,
            tableY:51,
            tableClass:'models.RoundTable' },
        { id:30,
            label:'21J',
            numberOfOccupants:1,
            occupied:false,
            rotation:295,
            x:-54,
            y:54,
            tableId:20,
            tableX:37,
            tableY:51,
            tableClass:'models.RoundTable' },
        { id:31,
            label:'21L',
            numberOfOccupants:1,
            occupied:false,
            rotation:327.95742485711503,
            x:-75,
            y:16,
            tableId:20,
            tableX:37,
            tableY:51,
            tableClass:'models.RoundTable' },
        { id:33,
            label:'44A',
            numberOfOccupants:1,
            occupied:false,
            rotation:-0.4077181089485009,
            x:-59,
            y:-21,
            tableId:32,
            tableX:25,
            tableY:116,
            tableClass:'models.RoundTable' },
        { id:34,
            label:'44B',
            numberOfOccupants:1,
            occupied:false,
            rotation:40.14098383507688,
            x:-31,
            y:-54,
            tableId:32,
            tableX:25,
            tableY:116,
            tableClass:'models.RoundTable' },
        { id:35,
            label:'44C',
            numberOfOccupants:1,
            occupied:false,
            rotation:79.1623470457217,
            x:10,
            y:-62,
            tableId:32,
            tableX:25,
            tableY:116,
            tableClass:'models.RoundTable' },
        { id:36,
            label:'44D',
            numberOfOccupants:1,
            occupied:false,
            rotation:120.1944289077348,
            x:48,
            y:-40,
            tableId:32,
            tableX:25,
            tableY:116,
            tableClass:'models.RoundTable' },
        { id:37,
            label:'44E',
            numberOfOccupants:1,
            occupied:false,
            rotation:160,
            x:63,
            y:0,
            tableId:32,
            tableX:25,
            tableY:116,
            tableClass:'models.RoundTable' },
        { id:38,
            label:'44F',
            numberOfOccupants:1,
            occupied:false,
            rotation:199.8055710922652,
            x:48,
            y:40,
            tableId:32,
            tableX:25,
            tableY:116,
            tableClass:'models.RoundTable' },
        { id:39,
            label:'44G',
            numberOfOccupants:1,
            occupied:false,
            rotation:240.8376529542783,
            x:10,
            y:62,
            tableId:32,
            tableX:25,
            tableY:116,
            tableClass:'models.RoundTable' },
        { id:40,
            label:'44H',
            numberOfOccupants:1,
            occupied:false,
            rotation:279.8590161649231,
            x:-31,
            y:54,
            tableId:32,
            tableX:25,
            tableY:116,
            tableClass:'models.RoundTable' },
        { id:41,
            label:'44I',
            numberOfOccupants:1,
            occupied:false,
            rotation:320.40771810894853,
            x:-59,
            y:21,
            tableId:32,
            tableX:25,
            tableY:116,
            tableClass:'models.RoundTable' },
        { id:43,
            label:'16',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:42,
            tableX:55,
            tableY:2,
            tableClass:'models.GenericTable' },
        { id:45,
            label:'17',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:44,
            tableX:55,
            tableY:9,
            tableClass:'models.GenericTable' },
        { id:47,
            label:'18',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:46,
            tableX:55,
            tableY:16,
            tableClass:'models.GenericTable' },
        { id:49,
            label:'19',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:48,
            tableX:55,
            tableY:23,
            tableClass:'models.GenericTable' },
        { id:51,
            label:'20',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:50,
            tableX:55,
            tableY:30,
            tableClass:'models.GenericTable' },
        { id:53,
            label:'02',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:52,
            tableX:11,
            tableY:20,
            tableClass:'models.GenericTable' },
        { id:55,
            label:'03',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:54,
            tableX:15,
            tableY:20,
            tableClass:'models.GenericTable' },
        { id:57,
            label:'04',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:56,
            tableX:11,
            tableY:27,
            tableClass:'models.GenericTable' },
        { id:59,
            label:'05',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:58,
            tableX:15,
            tableY:27,
            tableClass:'models.GenericTable' },
        { id:61,
            label:'10',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:60,
            tableX:35,
            tableY:20,
            tableClass:'models.GenericTable' },
        { id:63,
            label:'11',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:62,
            tableX:40,
            tableY:20,
            tableClass:'models.GenericTable' },
        { id:65,
            label:'12',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:64,
            tableX:35,
            tableY:27,
            tableClass:'models.GenericTable' },
        { id:67,
            label:'13',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:66,
            tableX:40,
            tableY:27,
            tableClass:'models.GenericTable' },
        { id:69,
            label:'14',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:68,
            tableX:35,
            tableY:34,
            tableClass:'models.GenericTable' },
        { id:71,
            label:'15',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:70,
            tableX:40,
            tableY:34,
            tableClass:'models.GenericTable' },
        { id:73,
            label:'06',
            numberOfOccupants:2,
            occupied:false,
            rotation:90,
            x:0,
            y:0,
            tableId:72,
            tableX:13,
            tableY:34,
            tableClass:'models.GenericTable' },
        { id:75,
            label:'07',
            numberOfOccupants:2,
            occupied:false,
            rotation:90,
            x:0,
            y:0,
            tableId:74,
            tableX:13,
            tableY:39,
            tableClass:'models.GenericTable' },
        { id:77,
            label:'08',
            numberOfOccupants:2,
            occupied:false,
            rotation:90,
            x:0,
            y:0,
            tableId:76,
            tableX:13,
            tableY:44,
            tableClass:'models.GenericTable' },
        { id:79,
            label:'22',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:78,
            tableX:11,
            tableY:51,
            tableClass:'models.GenericTable' },
        { id:81,
            label:'23',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:80,
            tableX:15,
            tableY:51,
            tableClass:'models.GenericTable' },
        { id:83,
            label:'24',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:82,
            tableX:11,
            tableY:58,
            tableClass:'models.GenericTable' },
        { id:85,
            label:'25',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:84,
            tableX:15,
            tableY:58,
            tableClass:'models.GenericTable' },
        { id:87,
            label:'26',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:86,
            tableX:11,
            tableY:65,
            tableClass:'models.GenericTable' },
        { id:89,
            label:'27',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:88,
            tableX:16,
            tableY:65,
            tableClass:'models.GenericTable' },
        { id:91,
            label:'28',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:90,
            tableX:21,
            tableY:65,
            tableClass:'models.GenericTable' },
        { id:93,
            label:'29',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:92,
            tableX:11,
            tableY:72,
            tableClass:'models.GenericTable' },
        { id:95,
            label:'30',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:94,
            tableX:16,
            tableY:72,
            tableClass:'models.GenericTable' },
        { id:97,
            label:'31',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:96,
            tableX:21,
            tableY:72,
            tableClass:'models.GenericTable' },
        { id:99,
            label:'32',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:98,
            tableX:11,
            tableY:79,
            tableClass:'models.GenericTable' },
        { id:101,
            label:'33',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:100,
            tableX:15,
            tableY:79,
            tableClass:'models.GenericTable' },
        { id:103,
            label:'33A',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:102,
            tableX:19,
            tableY:79,
            tableClass:'models.GenericTable' },
        { id:105,
            label:'35',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:104,
            tableX:33,
            tableY:84,
            tableClass:'models.GenericTable' },
        { id:107,
            label:'34',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:106,
            tableX:38,
            tableY:84,
            tableClass:'models.GenericTable' },
        { id:109,
            label:'37',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:108,
            tableX:33,
            tableY:91,
            tableClass:'models.GenericTable' },
        { id:111,
            label:'36',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:110,
            tableX:38,
            tableY:91,
            tableClass:'models.GenericTable' },
        { id:113,
            label:'38A',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:112,
            tableX:33,
            tableY:98,
            tableClass:'models.GenericTable' },
        { id:115,
            label:'38',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:114,
            tableX:38,
            tableY:98,
            tableClass:'models.GenericTable' },
        { id:117,
            label:'40',
            numberOfOccupants:2,
            occupied:false,
            rotation:90,
            x:0,
            y:0,
            tableId:116,
            tableX:47,
            tableY:100,
            tableClass:'models.GenericTable' },
        { id:119,
            label:'39',
            numberOfOccupants:2,
            occupied:false,
            rotation:90,
            x:0,
            y:0,
            tableId:118,
            tableX:47,
            tableY:104,
            tableClass:'models.GenericTable' },
        { id:121,
            label:'42',
            numberOfOccupants:2,
            occupied:false,
            rotation:90,
            x:0,
            y:0,
            tableId:120,
            tableX:54,
            tableY:100,
            tableClass:'models.GenericTable' },
        { id:123,
            label:'41',
            numberOfOccupants:2,
            occupied:false,
            rotation:90,
            x:0,
            y:0,
            tableId:122,
            tableX:54,
            tableY:104,
            tableClass:'models.GenericTable' },
        { id:125,
            label:'43A',
            numberOfOccupants:2,
            occupied:false,
            rotation:90,
            x:0,
            y:0,
            tableId:124,
            tableX:61,
            tableY:100,
            tableClass:'models.GenericTable' },
        { id:127,
            label:'43',
            numberOfOccupants:2,
            occupied:false,
            rotation:90,
            x:0,
            y:0,
            tableId:126,
            tableX:61,
            tableY:104,
            tableClass:'models.GenericTable' },
        { id:129,
            label:'45',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:128,
            tableX:47,
            tableY:115,
            tableClass:'models.GenericTable' },
        { id:131,
            label:'46',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:130,
            tableX:52,
            tableY:115,
            tableClass:'models.GenericTable' },
        { id:133,
            label:'47',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:132,
            tableX:59,
            tableY:115,
            tableClass:'models.GenericTable' },
        { id:135,
            label:'48',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:134,
            tableX:64,
            tableY:115,
            tableClass:'models.GenericTable' },
        { id:137,
            label:'49',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:136,
            tableX:71,
            tableY:115,
            tableClass:'models.GenericTable' },
        { id:139,
            label:'50',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:138,
            tableX:75,
            tableY:115,
            tableClass:'models.GenericTable' },
        { id:141,
            label:'51',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:140,
            tableX:79,
            tableY:115,
            tableClass:'models.GenericTable' },
        { id:143,
            label:'52',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:142,
            tableX:45,
            tableY:130,
            tableClass:'models.GenericTable' },
        { id:145,
            label:'53',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:144,
            tableX:49,
            tableY:130,
            tableClass:'models.GenericTable' },
        { id:147,
            label:'55',
            numberOfOccupants:2,
            occupied:false,
            rotation:90,
            x:0,
            y:0,
            tableId:146,
            tableX:56,
            tableY:126,
            tableClass:'models.GenericTable' },
        { id:149,
            label:'54',
            numberOfOccupants:2,
            occupied:false,
            rotation:90,
            x:0,
            y:0,
            tableId:148,
            tableX:56,
            tableY:130,
            tableClass:'models.GenericTable' },
        { id:151,
            label:'56',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:150,
            tableX:67,
            tableY:128,
            tableClass:'models.GenericTable' },
        { id:153,
            label:'57',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:152,
            tableX:71,
            tableY:128,
            tableClass:'models.GenericTable' },
        { id:155,
            label:'58',
            numberOfOccupants:2,
            occupied:false,
            rotation:0,
            x:0,
            y:0,
            tableId:154,
            tableX:75,
            tableY:128,
            tableClass:'models.GenericTable' }
    ] }
